import turtle
t = turtle.Turtle()
s = turtle.Screen()
s.setup(width=800, height=600)
s.bgcolor("#FFF9E6")
t.pensize(3)
t.speed(8)
t.hideturtle()

def dibujar_rectangulo(x, y, ancho, alto, color):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color(color)
    t.begin_fill()
    for _ in range(2):
        t.forward(ancho)
        t.left(90)
        t.forward(alto)
        t.left(90)
    t.end_fill()
dibujar_rectangulo(-120, -50, 240, 60, "#5C2C16")
dibujar_rectangulo(-90, 10, 180, 50, "#E67E22")
dibujar_rectangulo(-60, 60, 120, 50, "#E91E63")
t.penup()
t.goto(-5, 110)
t.pendown()
t.color("#F1C40F") 
t.begin_fill()
for _ in range(2):
    t.forward(10)
    t.left(90)
    t.forward(30)
    t.left(90)
t.end_fill()

t.penup()
t.goto(0, 145)
t.pendown()
t.color("#FF5722") 
t.begin_fill()
t.circle(7)
t.end_fill()
t.penup()
t.color("#2C3E50")
t.goto(0, -120)
t.write("¡Feliz Cumpleaños, More! 🎂" "te quiero muchisimo", align="center", font=("Arial", 24, "bold"))
turtle.done()